services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      - 'WATCHTOWER_CLEANUP=true'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: docsinvidiousio_docs_1
